### ISSUE TITLE
Logchecker says checksum invalid, but it's fine according to EAC online check

### ISSUE THREAD

**Issue by jorniste** [OPSnet/Logchecker#12]
This is using logchecker 0.9.6.
ID on site is 615177

**Comment by itismadness** [comment]
That ID on OPS points to a log file for Terry Riley's In C Mali that checks out 100% with valid checksum. 

Also, what EAC online check are you using? Can you provide a link?

**Comment by jorniste** [comment]
http://www.exactaudiocopy.de/log/check.aspx

Hmm, it seems there was a dependency issue when upgrading debian, I reinstalled the dependencies and now it shows checksum_ok.
